### ISSUE TITLE
Possible Blob Storage error

### ISSUE THREAD

**Issue by sqltj** [Microsoft/sql-server-samples#300] opened 2017-10-09 13:17 UTC
Is the blob store used for loading the ContosoDW sample still online and in the desired state? I get this error when attempting to create an External Table.

> EXTERNAL TABLE access failed due to internal error: 'Java exception raised on call to HdfsBridge_Connect. Java exception message:
> Parameters provided to connect to the Azure storage account are not valid.: Error [Parameters provided to connect to the Azure storage account are not valid.] occurred while accessing external file.'

**Comment by sqltj** [comment] 2017-10-09 19:59
I just updated my previous comment. I was referring to the blob store used to load the ContosoDW sample. The only steps I took were to create my SQL DW and attempt to load the script. The script fails with that error on the creation of the first external table.

**Comment by sfibich** [comment] 2017-10-19 13:11
I am having the exact same problem: 

ERROR:
Msg 105019, Level 16, State 1, Line 60
EXTERNAL TABLE access failed due to internal error: 'Java exception raised on call to HdfsBridge_Connect. Java exception message:
Parameters provided to connect to the Azure storage account are not valid.: Error [Parameters provided to connect to the Azure storage account are not valid.] occurred while accessing external file.'


CODE: 

-- Create an external data source
-- TYPE: HADOOP - PolyBase uses Hadoop APIs to access data in Azure blob storage.
-- LOCATION: Provide Azure storage account name and blob container name.
-- CREDENTIAL: Provide the credential created in the previous step.

CREATE EXTERNAL DATA SOURCE AzureStorage_west_public
WITH 
(  
    TYPE = Hadoop 
,   LOCATION = 'wasbs://contosoretaildw-tables@contosoretaildw.blob.core.windows.net/'
); 
GO



-- The data is stored in text files in Azure blob storage, and each field is separated with a delimiter. 
-- Run this [CREATE EXTERNAL FILE FORMAT][] command to specify the format of the data in the text files. 
-- he Contoso data is uncompressed and pipe delimited.

CREATE EXTERNAL FILE FORMAT TextFileFormat 
WITH 
(   FORMAT_TYPE = DELIMITEDTEXT
,	FORMAT_OPTIONS	(   FIELD_TERMINATOR = '|'
					,	STRING_DELIMITER = ''
					,	DATE_FORMAT		 = 'yyyy-MM-dd HH:mm:ss.fff'
					,	USE_TYPE_DEFAULT = FALSE 
					)
);
GO

-- To create a place to store the Contoso data in your database, create a schema.

CREATE SCHEMA [asb];
GO


-- Now let's create the external tables. All we are doing here is defining column names and data types, 
-- and binding them to the location and format of the Azure blob storage files. The location is the folder 
-- under the root directory of the Azure Storage Blob.

--DimAccount
CREATE EXTERNAL TABLE [asb].DimAccount 
(
	[AccountKey] [int] NOT NULL,
	[ParentAccountKey] [int] NULL,
	[AccountLabel] [nvarchar](100) NULL,
	[AccountName] [nvarchar](50) NULL,
	[AccountDescription] [nvarchar](50) NULL,
	[AccountType] [nvarchar](50) NULL,
	[Operator] [nvarchar](50) NULL,
	[CustomMembers] [nvarchar](300) NULL,
	[ValueType] [nvarchar](50) NULL,
	[CustomMemberOptions] [nvarchar](200) NULL,
	[ETLLoadID] [int] NULL,
	[LoadDate] [datetime] NULL,
	[UpdateDate] [datetime] NULL
)
WITH 
(
    LOCATION='DimAccount/' 
,   DATA_SOURCE = AzureStorage_west_public
,   FILE_FORMAT = TextFileFormat
,   REJECT_TYPE = VALUE
,   REJECT_VALUE = 0
)
;

**Comment by jodebrui** [comment] 2018-03-27 23:06
This is a duplicate of the following issue: https://github.com/Microsoft/sql-server-samples/issues/304
Issue #304 will be updated once this issue is resolved

**Closed by jodebrui** 2018-03-27 23:06 UTC
