### ISSUE TITLE
Node Js / Express Example is Broken

### ISSUE THREAD

**Issue by AlexAscherson** [Microsoft/sql-server-samples#203] opened 2017-03-27 15:15 UTC
sql-server-samples/samples/features/json/todo-app/nodejs-express4-rest-api/

Hi guys,

Thanks for all the help with the samples and examples.  Unfortunately I can't seem to get the express app to work, and have spent about 5 hours today trying to understand whats wrong with it.

At first I was unable to connect to the database on Azure, though this was an issue with the docs not mentioning that you must whitelist your IP to connect, which is important info for someone new to this process and setting up an account for the first time.

The connection appears to be working, however the app seems to stall at this point, and its unclear if any sql is being executed or if nothing is being returned.

I'm not a node expert, so maybe im missing something obvious.  At present however, it seems that there are no working routes in the app that will produce a page, which I am guessing their should be?

Apologies if I am missing a key step, if the app is not supposed to produce any visible pages can that be made clear?

My understanding is that hitting the todo/ route should generate a list of to-dos from the database.  At present there seems to be no response.

The last debug message I see is:

State Change: LoggedINSendingInitialSQL- > Loggedin

The the connected event fires, but nothing I can see after that.

**Comment by jovanpop-msft** [comment] 2017-03-29 21:30
Hi, could you take a new version? I have changed db.js and added more log info. I have setup Azure SQL Database updated connection info in db.js, started node app.js and opened http://localhost:3000/todo and list of todo items formatted as JSON are shown. You will be able to see more debug messages if it does not work. Maybe you can also run npm install to refresh packages.

**Comment by jovanpop-msft** [comment] 2017-04-08 17:31
Hi @AlexAscherson, could you download it again and check does it works? Today I had a session where I have used this code and it worked fine. I would like to close this issue when you confirm that it works.

**Comment by AlexAscherson** [comment] 2017-04-08 20:23
Hi Jovan,

Thanks so much for the help! I will make the time to check it this weekend
/ early this week.  Sorry for the delay, been v. busy but haven't forgotten
about it.

**Comment by jovanpop-msft** [comment] 2017-05-08 12:32
I have refactored the code, checked-in new version, and it works on my environment. I will close this issue because I cannot reproduce the problem. Feel free to report new one with the new code if you find some issue.

**Closed by jovanpop-msft** 2017-05-08 12:32 UTC
