### ISSUE TITLE
SQL Server 2016 WorldWideImporters sample file not importing

### ISSUE THREAD

**Issue by Crabbab489** [Microsoft/sql-server-samples#343] opened 2017-12-14 17:38 UTC
I’m on sql server 2016 Enterprise Edition Sp1. restore is failing with error:

5 percent processed.
10 percent processed.
15 percent processed.
20 percent processed.
25 percent processed.
30 percent processed.
Processed 1464 pages for database ‘WideWorldImporters’, file ‘WWI_Primary’ on file 1.
Processed 53096 pages for database ‘WideWorldImporters’, file ‘WWI_UserData’ on file 1.
Processed 33 pages for database ‘WideWorldImporters’, file ‘WWI_Log’ on file 1.
Processed 3862 pages for database ‘WideWorldImporters’, file ‘WWI_InMemory_Data_1’ on file 1.
Msg 41316, Level 16, State 0, Line 4
Restore operation failed for database ‘WideWorldImporters’ with internal error code ‘0x82000009’.
Msg 3167, Level 16, State 1, Line 6
RESTORE could not start database ‘WideWorldImporters’.
Msg 3013, Level 16, State 1, Line 6
RESTORE DATABASE is terminating abnormally.
Msg 3414, Level 21, State 1, Line 6
An error occurred during recovery, preventing the database ‘WideWorldImporters’ (10:0) from restarting. Diagnose the recovery errors and fix them, or restore from a known good backup. If errors are not corrected or expected, contact Technical Support.

**Comment by jodebrui** [comment] 2017-12-18 20:55
This error indicates an issue with the compilation of memory-optimized tables, which happens during database startup, which itself happens as part of restore. For more details about this compilation process see: https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/native-compilation-of-tables-and-stored-procedures#security-considerations-for-native-compilation

Note that the compilation of memory-optimized tables involves the VC compiler, which can be found under the SQL Server installation folder under ‘MSSQL\Binn\Xtp\VC\bin’.

Two potential causes for the error:

  *   The SQL Server installation is corrupted, meaning that either files are missing or the contents have changed, for example due to a bit-flip on the installation drive. This can be addressed by performing a repair of the SQL Server installation.
  *   The server has software such as AppLocker with restrictive execution policies either preventing the execution of the VC compiler vc.exe or preventing SQL Server from loading generated DLLs. Execution of the VC compiler must be permitted and the sqlservr.exe process must be permitted to load generated DLLs, which are placed under ‘MSSQL\DATA\xtp’ (assuming you are using the default data directory).

In order to narrow down the issue, you can enable additional tracing in the SQL Server error log using trace flag 9830:
                DBCC TRACEON (9830, -1)

Successful compilation of a table will look something like:

**Comment by jodebrui** [comment] 2017-12-18 20:57
[hit sent too soon]

This error indicates an issue with the compilation of memory-optimized tables, which happens during database startup, which itself happens as part of restore. For more details about this compilation process see: https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/native-compilation-of-tables-and-stored-procedures#security-considerations-for-native-compilation

Note that the compilation of memory-optimized tables involves the VC compiler, which can be found under the SQL Server installation folder under ‘MSSQL\Binn\Xtp\VC\bin’.

Two potential causes for the error:

  *   The SQL Server installation is corrupted, meaning that either files are missing or the contents have changed, for example due to a bit-flip on the installation drive. This can be addressed by performing a repair of the SQL Server installation.
  *   The server has software such as AppLocker with restrictive execution policies either preventing the execution of the VC compiler vc.exe or preventing SQL Server from loading generated DLLs. Execution of the VC compiler must be permitted and the sqlservr.exe process must be permitted to load generated DLLs, which are placed under ‘MSSQL\DATA\xtp’ (assuming you are using the default data directory).

In order to narrow down the issue, you can enable additional tracing in the SQL Server error log using trace flag 9830:
                DBCC TRACEON (9830, -1)

Successful compilation of a table will look something like:
[cid:image001.png@01D377FF.C7C4DDD0]

If we know at which stage of the compilation process the failure occurs, and with hopefully more information in the errorlog, we can further narrow down the cause of the restore failure.
Could you enable trace flag 9830, retry the restore, and share the SQL Server errorlog? You can find the errorlog under the SQL Server installation folder: ‘MSSQL\Log\ERRORLOG’.

Thanks,
Jos

**Comment by jodebrui** [comment] 2018-03-27 22:48
Closing as no response in last few months

**Closed by jodebrui** 2018-03-27 22:48 UTC
